### ISSUE TITLE
Android Microphone indicator shows green while i muted my mic ()

### ISSUE THREAD

**Issue by smaznet** [flutter-webrtc/flutter-webrtc#1008]
**Describe the bug**
im using sip_ua package for calls and i used  `_call.mute(true, false); `method to mute audio when user tap mic icon
but while its muted green indicator is not gone
![image](https://user-images.githubusercontent.com/10239885/179352216-9c29c558-e7ba-44b1-a567-be4ef8ba89fa.png)

**Comment by ycherniavskyi** [comment]
For such cases, you need to track actual methods calls and then analyze must mic disabled at all. From my 5 min investigation, I can say that no, it must not, because [it only disables track](https://github.com/flutter-webrtc/dart-sip-ua/blob/8051ebe642255bdff9caa5ea7f9280303aea6a56/lib/src/rtc_session.dart#L2912).

But if you think that it must, then you need to create an issue in [dart-sip-ua](https://github.com/flutter-webrtc/dart-sip-ua).
