### ISSUE TITLE
Incorporate go-flutter desktop

### ISSUE THREAD

**Issue by joeblew99** [flutter-webrtc/flutter-webrtc#119]
Could be also add go-flutter support ?

I have been playing with Video in go-flutter as it support textures now. It works but is slow for now.  Its uses ffpmeg under the hood to handle the video frames. Its only going to get better too due to the fantastic team over at go-flutter and quite a few plugin and developers getting onboard.

More info here:
https://github.com/go-flutter-desktop/plugins/tree/plugin/video_player

**Comment by cloudwebrtc** [comment]
go-flutter requires a go-lang plugin, and flutter-webrtc is a native plugin. You should need to make a side-by-side interface on the go-flutter plugin system, allowing go-plugin and native-plugin to register to flutter-engine at the same time.

**Comment by joeblew99** [comment]
Can you explain a bit more .
I think you mea that the golang code would need to call your native plugin

**Comment by cloudwebrtc** [comment]
Yes, need go-flutter support native plugin, I think this is a challenge.

**Comment by joeblew99** [comment]
Can you be more clear about the challenges ?

go-flutter already calls into c++ code like the flutter engine.
For Webrtc, the golang code woud call into your web rtc c++ engine ?

**Comment by cloudwebrtc** [comment]
go-flutter manages key-event, platform event, method channel, texture register, plugin register through its own set of code, all of which are implemented by go language, so the plugin is completely implemented by go.

Flutter native also uses another set of client_warpper_cpp code to manage key-event, platform event, plugin register, texture register ... etc, so the registration plugin can only be implemented by cpp.

The only place where go-flutter and flutter native are intersected is embedder.dll/so, and this dynamic library is a low-level API. For plugins, you need an advanced management API.
Because the plugin requires MethodChannel\Texture Register etc, these are difficult to call each other if the plugin language is completely different.

I think there is a possibility to insert a client_warpper_cpp API between embedder.dll and embedder-go so that the native plugin can be registered, but it will be very difficult.

## go-flutter on the left and flutter native on the right:
![image](https://user-images.githubusercontent.com/17733746/63363764-c9d9ea80-c3a6-11e9-8067-cf707d41c0b6.png)

**Comment by joeblew99** [comment]
@cloudwebrtc 

Its really nice of you to take the time to make this diagram and explanation.

So if i answer from the declared terms in your diagram:

go-flutter has the Texture Plugin ( as you know i think ) working. It currently can play video. 
go-flutter has the Audio Plugin working
go-flutter has no Webcam Plugin yet, but present in many golang libs around that do this cross platform. go opencv and many others.

So then this opens the door for the golang code that imports these plugins to call the flutter-webrtc.dll shared object and also get returned data also and back into the go-flutter GUI.

This reminds me of the zserge lib that wraps all the Webviews for desktop.
https://github.com/zserge/webview/tree/webview-x





Maybe i am missing something.
