### ISSUE TITLE
On Web, both local and remote streams show only remote stream until window is resized

### ISSUE THREAD

**Issue by cadaniel** [flutter-webrtc/flutter-webrtc#270]
**Describe the bug**

When starting a call, I noticed that it will only show the remote stream until the window is resized.

**To Reproduce**

![Screen Recording 2020-06-01 at 6 06 40 PM](https://user-images.githubusercontent.com/5515671/83459955-4cfa9780-a433-11ea-900b-4915a73208ed.gif)

**Expected behavior**

Stream shows both local and remote broadcasts

**Platform information**

* **Flutter version**: 
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-CA)
    • Flutter version 1.18.0-11.1.pre at /Users/archer/flutter/flutter
    • Framework revision 2738a1148b (3 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

* **Plugin version**:
0.2.8
* **OS**: 
* **OS version**:
Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by wer-mathurin** [comment]
@cadaniel : try the lastest version of the library.  From what I see in the code, the widget is now statefull and listen for renderer value change.

Feel free to reopen if you still encounter the problem.

**Comment by arafat1** [comment]
I see that RTCVideoView widget is still stateless. I am experiencing a similar issue. In my video-conferencing app whenever a participant drops the call and I replace the previous stream with a new stream in the renderer, the new stream does not display. The workaround that works is to create a new renderer with each new stream, which sounds wasteful and also leads to slight flicker on the screen. Unfortunately I can not share the code as it is proprietary

**Comment by wer-mathurin** [comment]
@arafat1 I think the problem is how flutter decide to re-render the widget itself, if you don't pass a key to the widget, so when it comes time to decide if the widget will re-redraw, it will not...since the default behaviors is only looking if the runtime type is the same.

Have  you tried to pass something like LocalKey(stream) to the RTCVideoView.  If you use a state management solution to wrap this widget, it will pass the new value, so I think this will do the trick.  I didn't tested it, so be indulgent with me!

**Comment by arafat1** [comment]
@wer-mathurin Indeed it was the case of missing key in the wrapper widget. Appreciate the quick response.
