### ISSUE TITLE
Create a serverless webrtc function (webrtc without signaling server) for local connections.

### ISSUE THREAD

**Issue by danteCarvalho** [flutter-webrtc/flutter-webrtc#296]
**Is your feature request related to a problem? Please describe.**
The current implementation only works with a server on a pc.

**Describe the solution you'd like**
I found a android implementation  that is focused on local connetions here https://github.com/meshenger-app/meshenger-android , with their app you can scan a qrCode generated with the phone informations and start the webrtc with it. And it works with tethering which is weird , because on their FAQ they say it does not work, but i just tested and it worked! (i want to use it with tethering if possible, with the phone as a router)

**Describe alternatives you've considered**

**Additional context**

**Comment by ycherniavskyi** [comment]
Hmm, WebRTC does not declare/regulate any signaling, so [flutter-webrtc](/flutter-webrtc/flutter-webrtc) does not do this either. It is up to you to implement the way to exchange `RTCSessionDescription` object data between peers. The server is just the most common way to do it (and as I know there no any server implementation in this project).

So from my point of view, this issue is not related to this plugin and should be closed.

**Comment by danteCarvalho** [comment]
I guess i had understood it the wrong way, the server only works to exchange information. So after peers connect, the server receives no more data, right?  ok better close the issue.

**Comment by ycherniavskyi** [comment]
@danteCarvalho in general after peers connect there no additional signaling exchange related to WebRTC happens, except for [`RTCPeerConnection.restartIce()`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/restartIce) maybe.
