### ISSUE TITLE
Unable to getUserMedia on macos

### ISSUE THREAD

**Issue by tomhaitao** [flutter-webrtc/flutter-webrtc#308]
Unable to getUserMedia: NotFoundError
<img width="713" alt="WX20200812-145659@2x" src="https://user-images.githubusercontent.com/15882629/89984725-77c36080-dcac-11ea-91c0-c4d80f904b97.png">

**Comment by cloudwebrtc** [comment]
If your system version is `Catalina` and you use the `Terminal` or `VSCode` to run a flutter app, you need to add `Terminal` and `VSCode` to `Microphone` and camera access permissions in `System -> Security & Privacy -> Privacy`. Because these programs indirectly start flutter apps, but they do not declare permission tags in the app.

**Comment by mafreud** [comment]
In my case, these checks are required to solve this issue.

<img width="301" alt="Image" src="https://github.com/user-attachments/assets/7a2eacda-044f-4564-b830-46f6a5e1b30f" />

**Comment by scognito** [comment]
@mafreud thanks, it worked!

**Comment by mafreud** [comment]
@scognito you are welcome!
