### ISSUE TITLE
How Can I add camera effects - filters

### ISSUE THREAD

**Issue by K12AZ** [flutter-webrtc/flutter-webrtc#361]
Hello, 

Did anyone know how can we add camera effects and transmit them to peer connection? 

For example Snapchat like filters or open GL filters

Appreciate it if anyone able to give a solution or guiding to how to do it 

TIA

**Comment by linhnguyengas** [comment]
someone to help, please!
I also have to the same question

**Comment by K12AZ** [comment]
> someone to help, please!
> I also have to the same question
> ![tenor](https://user-images.githubusercontent.com/43808684/94908627-2ecda280-04cc-11eb-8e33-8108ce3922c6.gif)

I understand brother, I can feel the pain :(

**Comment by vuitv** [comment]
I also have to the same question

**Comment by cloudwebrtc** [comment]
@K12AZ  I have no experience with this, do we need to edit the texture to implement the filter?

**Comment by mrpvb-pvbk** [comment]
I think this should be implemented in a separate plugin. Because it uses a neural network.

**Comment by ChihayaK** [comment]
AFAIK its quite not possible to archive in the flutter end. But you can implement your own VideoProcessor class and set it in the videoSource.setVideoProcessor(YOUR_VIDEO_PROCESSOR) in GetUserMediaImpl.java when you get the user video. For the iOS part however, I find the WebRTC in objective c do not have the same VideoProcessor class. So I implement my own RTCVideoRenderer to extract the frames and implement another RTCVideoCapturer to capture and process the frame to a new video source.(Which is a very hacky solution) Maybe there is better ways for iOS, but thats all I know for now.

**Comment by KalanaPerera** [comment]
@[ChihayaK](https://github.com/ChihayaK) would you be able to guide the way you did? TIA

**Comment by ChihayaK** [comment]
> @[ChihayaK](https://github.com/ChihayaK) would you be able to guide the way you did? TIA

It is pretty clear above. You need to have some knowledge of Android development (particularly Java) and iOS development (particularly Objective C). I suggest the first step is to look in the GetUserMediaImpl.java file and you will find the get user media function (if I recall correctly). You will find out that you have the ability to extract and modify individual frames. Then you can do whatever you want because it's just like a bitmap. (obviously you need to convert the frames from yuv to normal bgr)

**Comment by KalanaPerera** [comment]
> > @[ChihayaK](https://github.com/ChihayaK) would you be able to guide the way you did? TIA
> 
> It is pretty clear above. You need to have some knowledge of Android development (particularly Java) and iOS development (particularly Objective C). I suggest the first step is to look in the GetUserMediaImpl.java file and you will find the get user media function (if I recall correctly). You will find out that you have the ability to extract and modify individual frames. Then you can do whatever you want because it's just like a bitmap. (obviously you need to convert the frames from yuv to normal bgr)

I'll have a look, thank you.

**Comment by ChihayaK** [comment]
> > > @[ChihayaK](https://github.com/ChihayaK) would you be able to guide the way you did? TIA
> > 
> > 
> > It is pretty clear above. You need to have some knowledge of Android development (particularly Java) and iOS development (particularly Objective C). I suggest the first step is to look in the GetUserMediaImpl.java file and you will find the get user media function (if I recall correctly). You will find out that you have the ability to extract and modify individual frames. Then you can do whatever you want because it's just like a bitmap. (obviously you need to convert the frames from yuv to normal bgr)
> 
> I'll have a look, thank you.

For android. I am sure you will encounter problems with the yuv to bitmap conversion. If you want to do realtime effects, I suggest building the [libyuv](https://chromium.googlesource.com/libyuv/libyuv/)(because it is ultra fast) and including the library on the android side. The yuv helper function seems to have minor issues.

**Comment by KalanaPerera** [comment]
@[ChihayaK](https://github.com/ChihayaK) Thank you for the heads-up, yes I am planning to add real-time filters(effects) via WEBRTC, 

Sorry to ask, Do you have any working codebase, I am interested in even purchasing if you are down.

**Comment by ChihayaK** [comment]
> @[ChihayaK](https://github.com/ChihayaK) Thank you for the heads-up, yes I am planning to add real-time filters(effects) via WEBRTC,
> 
> Sorry to ask, Do you have any working codebase, I am interested in even purchasing if you are down.

Sorry, I do not own that piece of code, so I just can't send the code to you. But I will not mind sharing my knowledge here (if I have time). :rofl:

**Comment by KalanaPerera** [comment]
> > @[ChihayaK](https://github.com/ChihayaK) Thank you for the heads-up, yes I am planning to add real-time filters(effects) via WEBRTC,
> > Sorry to ask, Do you have any working codebase, I am interested in even purchasing if you are down.
> 
> Sorry, I do not own that piece of code, so I just can't send the code to you. But I will not mind sharing my knowledge here (if I have time). 🤣

Okay got it, Thank you.

**Comment by KalanaPerera** [comment]
@ChihayaK - What do you think about this solution? would you be able to have a look?

https://github.com/flutter-webrtc/flutter-webrtc/pull/813

**Comment by ChihayaK** [comment]
> @ChihayaK - What do you think about this solution? would you be able to have a look?
> 
> #813

I spent a little time looking into this PR. So the first thing I noticed is that there is no Android implementation, which you still need to figure out. The second thing is that this approach is very different from my own. This effectively allows you to send out any frame to the webrtc video stream. This is great, but I see potential issues here. You need to basically handle the camera device yourself in the dart language (which I am not quite familiar with), so you may run into some camera issues. For the audio, I am not sure how this approach handles it. And I was really confused when I looked into the audio part when I was developing my approach.(You can see the audio for the android part [here](https://github.com/flutter-webrtc/flutter-webrtc/blob/master/android/src/main/java/org/webrtc/audio/WebRtcAudioTrackUtils.java) and I had no idea how to process the auido stream at that time.) So my solution ended up using the audio track the webrtc "has" before, since I was intercepting the video stream only and could pass the audio tracks as normal. Which might be an issue here since it creates the video and audio tracks from the ground up. Lastly, I remembered that the webrtc will automatically adjust the video resolution based on the quality of the connection. This feature might be missing if you try to do it this way.

**Comment by KalanaPerera** [comment]
@ChihayaK Thank you for taking the time to have a look at the PR. also valuable feedback, appreciate it. 

Anyway, I've started doing my own one as you suggested. but since I don't have any experience with Android and IOS, :))

**Comment by cloudwebrtc** [comment]
I think a perfect way is to implement [insertable streams](https://developer.mozilla.org/en-US/docs/Web/API/Insertable_Streams_for_MediaStreamTrack_API)

This method allows the video or audio source to be passed to multiple filters, so that you can modify the audio/video raw data, including mixes, recordings, filters, and even image capture and insertion. Of course, e2ee encryption is also one of the functions.

**Comment by ChihayaK** [comment]
> I think a perfect way is to implement [insertable streams](https://developer.mozilla.org/en-US/docs/Web/API/Insertable_Streams_for_MediaStreamTrack_API)
> 
> This method allows the video or audio source to be passed to multiple filters, so that you can modify the audio/video raw data, including mixes, recordings, filters, and even image capture and insertion. Of course, e2ee encryption is also one of the functions.

This must be the perfect solution for the filter problem. 👍

**Comment by KalanaPerera** [comment]
Hi @cloudwebrtc 

Thank you for guiding us on the correct path. Do you have any estimated dates to start and release this feature? 

Let us know how can we help you to achieve this soonest.

**Comment by KalanaPerera** [comment]
Hi everyone

Thank you for your gudinf on this, but I couldn't able to get done with this :(( , and finally, I found the solution on the Agora. 

Hope this helps someone who looking for implementing AR (DEEPAR) features with WEBRTC:

- sharing my findings: https://github.com/AgoraIO/Agora-Flutter-SDK/issues/615


Happy Coding! Cheers!
