### ISSUE TITLE
[Unified-Plan] Implementing onTrack for Android

### ISSUE THREAD

**Issue by Ayman-Kortobaa** [flutter-webrtc/flutter-webrtc#371]
Thanks again for this amazing package, and I am glad that the Unified Plan hit the master branch and ready for production.
We are using the Unified-Plan SDP semantics, and mostly receiving and sending tracks instead of streams.
The problem is that iOS doesn't support the `onAddTrack` method as it only has `didAddReceiver` but no `didAddTrack` callback for the native PeerConnection delegate.

I'd like to know what's the current issue with implementing `onTrack` for Android's PeerConnection Observer, does it have any issues or is it just forgotten commented out?

So in the current state of the package, we'll either have to use `onAddTrack` for Android and `onTrack`for iOS which doesn't seem right, or we get the `onTrack` method implemented for Android as it is commented out.

I'd love to help with this feature if feasible but I'd like to know why it is not implemented for Android or what issues are faced.

P.S: I have tried `onTrack` after uncommenting it for my app and it worked perfectly on Android.

**Comment by cloudwebrtc** [comment]
Judging from the current [`ontrack`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ontrack) standard, the onTrack event provides [`RTCTrackEvent`](https://developer.mozilla.org/en-US/docs/Web/API/RTCTrackEvent#Properties), which mainly contains:

## Properties
Since RTCTrackEvent is based on Event, its properties are also available.
`receiver` Read only
The RTCRtpReceiver used by the track that's been added to the RTCPeerConnection.
`streams` Read only Optional
An array of MediaStream objects, each representing one of the media streams to which the added track belongs. By default, the array is empty, indicating a streamless track.
`track` Read only
The MediaStreamTrack which has been added to the connection.
`transceiver` Read only
The RTCRtpTransceiver being used by the new track.

Judging from the current standard, the `onTrack` event provides RTCTrackEvent, which mainly contains
Among them, the `transceiver ` is always called by the native `onTrack` function, so it cannot be output at the same time, so the output `receiver`,`streams`,`track` is preferred, then the RTCVideoRenderer can be rendered to the video in the first time because it needs `streams[0]`

**Comment by cloudwebrtc** [comment]
@Ayman-Kortobaa I created a PR, you can test whether it is what you need
