### ISSUE TITLE
Using the track received from ontrack in unified plan

### ISSUE THREAD

**Issue by igala** [flutter-webrtc/flutter-webrtc#390]
How should a track be played when received.

I tried adding it to a stream created locally but it fails.

Any suggestions?

**Comment by Ayman-Kortobaa** [comment]
Can you share your code?
Audio tracks are handled on the native side, the `stream` containing Video `track`s has to be added to a `RTCVideoRenderer`'s `srcObject` then viewed in `RTCVideoView`.
The example in the package can help you get started.

**Comment by igala** [comment]
Below is a code snippet from janus.js from the onTrack callback under the unified plan branch:

`config.pc.ontrack = function(event) {
				Janus.log("Handling Remote Track");
				Janus.debug(event);
				if(!event.streams)
					return;
				config.remoteStream = event.streams[0];
				if(!event.track)
					return;
				// Notify about the new track event
				var mid = event.transceiver ? event.transceiver.mid : event.track.id;
				try {
					pluginHandle.onremotetrack(event.track, mid, true);
`

What goes back with the callback is track and mid.

on the application side it handles the track by cloning the track and adding it to a new stream created locally, then played with video view. Below is the snippet:

`stream = new MediaStream();
					stream.addTrack(track.clone());
					remoteFeed.remoteTracks[mid] = stream;`


How do you accomplish this with flutter webrtc?

**Comment by cloudwebrtc** [comment]
@igala https://github.com/flutter-webrtc/flutter-webrtc/blob/master/example/lib/src/loopback_sample.dart#L91

**Comment by igala** [comment]
Thank you,

I followed to code example and at first it looks like it worked , but entering a room with multiple video tracks an using the stream received in the ontrack event, shows only one stream.

The stream received in the ontrack event holds the same stream for all mids.

It looks like a bug.

**Comment by itsthetaste** [comment]
I think I'm hitting that same issue.

I can have managed to get the mobile to web working, but the web to mobile isn't.

Inside my web js, inside my connection, I'm initially creating an inactive transceiver for both the audio and video.
Then when i want to send either audio or video, I do a getUserMedia, and replace the tracks in the appropriate transceivers and set their direction to sendonly, then negotiate.

In my flutter app, I'm seeing the onTrack fire twice, once for the audio (I ignore this as that handled internally), and then again with the video track.

For me though, the streams list is empty, so I cannot go and place it into the srcObject of my renderer.

This is what I can see in the debugger.
![image](https://user-images.githubusercontent.com/4565648/99923428-a0d4a200-2d2d-11eb-8cbb-acdfcebb5f66.png)

and this is when im seeing this, i.e., in my onTrack event
![image](https://user-images.githubusercontent.com/4565648/99923479-d7122180-2d2d-11eb-862f-dcb53042cfc5.png)

If I try and use the track, by appending it into a new MediaStream,

![image](https://user-images.githubusercontent.com/4565648/99923594-50aa0f80-2d2e-11eb-8d2f-7c8a16ea0d99.png)

I get an error

![image](https://user-images.githubusercontent.com/4565648/99923561-340dd780-2d2e-11eb-9988-c10cb082e6a3.png)

making me think, that internally the track doesn't exist.

I'm happy to get into the plugin and change things, but am not sure if this is expected behaviour, i.e., the streams is null, or where abouts you guys are at with the supporting tracks in this lib?  

@igala do you think its the same bug that you saw?

**Comment by cloudwebrtc** [comment]
ontrack will be triggered twice, once for audio and once for video, rendering can only be set when single video track is valid.
```dart
void _onTrack(RTCTrackEvent event) {
    if (event.track.kind == 'video' ) {
      _remoteRenderer.srcObject = event.streams[0];
    }
 }
```

**Comment by itsthetaste** [comment]
Hi @cloudwebrtc many thanks for the response, and this library :).  

I understand onTrack will be triggered twice, and that it's triggered by the remote side (when I receive their offer and set it into the remote description).
The event I have there is just because im structuring my signalling layer differently than you do, and I'm passing the onTrack event call up into a Provider.

I've been debugging further.

Working backwards from the call that sets the stream into the srcObject of the videoRenderer.

- This is trying to find the remoteStreams from the PeerConnectionObserver.
Inside the PeerConnectionObserver
- These get set and removed in the onAddStream/onRemoveStream handlers.
- But, this doesn't fire for me, so the remoteStreams and remoteTracks are empty.
- I can see the onAddTrack gets fired, but without any mediaStreams
- I can also see that the onTrack is fired, but it looks like your faking an onTrack from inside the onAddTrack, as the code within onTrack is commented out.

Which means, it looks like I'm not receiving a stream, which is right, as I never sent on from the other side.  I just added a transceiver and set its track and negotiated.  Checking what happens in my js lib, in the RTCTrackEvent, that also gives me an empty streams array.  But, I have the transceiver and the track so I just take that and append it into an new MediaStream before placing into the srcObject of a video element.

I appreciate, that this lib is not a web browser and you're trying to make it as close as possible.

I think I have a plan that might work, just to see if it works. 
I'm going to store the track that's inside the transceiver delivered in the onTrack into the remoteTracks inside the pco.
Then, im going to add another method call, "videoRendererSetSrcObjectWithTrack", get the remoteTrack.
Then, make in the FlutterRTCVideoRenderer, change setVideoTrack to public, and pass the track in.
Then, I think im going to have to add another property to the rtc_video_renderer_impl.dart, srcTrack, which I can then call like this;

```
void _onTrack(RTCTrackEvent event) {
  if (event.track.kind == 'video' ) {
    _remoteRenderer.srcTrack = event.track;
  }
}
```

I know this makes the api of this plugin not follow the standards.  I think really, it would be nice to be able to create a new MediaStream at the point of setting the srcObject.

```
void _onTrack(RTCTrackEvent event) {
  if (event.track.kind == 'video' ) {
    _remoteRenderer.srcObject = new MediaStream([event.track]);
  }
}
```

But I'm going to try the srcTrack idea first and see if it works.

**Comment by itsthetaste** [comment]
It works, I can now see the remote video.

A few issues.  I have nothing removing the remoteTrack, I think that should get removed when the transciever is killed.  But, I'm worried it might leak.  Also, adding the srcTrack is non spec compliant, so you might not want it like this.

Let me know your thoughts, want a PR, or new branch to see what i've done, get some feedback?

**Comment by cloudwebrtc** [comment]
I think `_remoteRenderer.srcObject = new MediaStream([event.track]);` This way is very good, no need to deviate from the standard.

**Comment by itsthetaste** [comment]
I've managed to get this working.

```
void _onTrack(RTCTrackEvent event) {
  if (event.track.kind == 'video' ) {
    MediaStream stream = await createLocalMediaStream(track.id); // can be anything
    await stream.addTrack(track);
    _remoteRenderer.srcObject = stream;
  }
}
```

By extending, mainly the getTrackForId method to get the connections transceivers, look through them and find the track.  Also a little fix in the getStreamForId so that if the pco is null, it doesn't try and query the remoteStreams.

```
MediaStream getStreamForId(String id, String peerConnectionId) {
    MediaStream stream = null;
    if (peerConnectionId.length() > 0) {
      PeerConnectionObserver pco = mPeerConnectionObservers.get(peerConnectionId);
      if (pco != null) {
        stream = pco.remoteStreams.get(id);
      }
    } else {
      for (Entry<String, PeerConnectionObserver> entry : mPeerConnectionObservers
              .entrySet()) {
        PeerConnectionObserver pco = entry.getValue();
        stream = pco.remoteStreams.get(id);
        if (stream != null) {
          break;
        }
      }
    }
    if (stream == null) {
      stream = localStreams.get(id);
    }

    return stream;
  }

  private MediaStreamTrack getTrackForId(String trackId) {
    Log.d(TAG, "££££££ getTrackForId: " + trackId);

    MediaStreamTrack track = localTracks.get(trackId);

    Log.d(TAG, "££££££ getTrackForId: track is null: " + (track == null));

    if (track == null) {
      for (Entry<String, PeerConnectionObserver> entry : mPeerConnectionObservers.entrySet()) {
        PeerConnectionObserver pco = entry.getValue();
        track = pco.remoteTracks.get(trackId);
        // check if its in the transceivers
        if (track == null) {
          List<RtpTransceiver> transceivers = pco.getTransceiversInternal();
          Log.d(TAG, "££££££ getTrackForId: transceivers: " + transceivers.size());
          for( RtpTransceiver transceiver : transceivers ) {
            RtpReceiver receiver = transceiver.getReceiver();
            Log.d(TAG, "££££££ getTrackForId: receiver is null: " + (receiver == null));
            if(receiver != null) {
              if (receiver.track() != null) {
                Log.d(TAG, "££££££ getTrackForId: track is not null id: " + receiver.track().id());
                if (receiver.track().id().equals(trackId)) {
                  Log.d(TAG, "££££££ getTrackForId: track id matches");
                  track = receiver.track();
                  break;
                }
              }
            }
          }
        }
        if (track != null) {
          break;
        }
      }
    }

    return track;
  }
```

Its not as elegant as the js method, but works using mostly what's already there.  Its not finished yet, need to work out how to attach the onended, onmute/onunmute handlers although, they don't appear to be in the google lib.  Also fix a bug when the remote connection sets one of its transceivers to inactive, both seem to stop.  So, still a bit left to do.

**Comment by wer-mathurin** [comment]
@itsthetaste I added sending onmute/onummute event in the dart implementation.   Maybe we can handle those cases in the dart implementation, **instead** than passing the logic in Android and iOS, and other implementation.

Also, I closing this ticket since you merged the PR.  Feel free to reopen if needed.

**Comment by igala** [comment]
This works great with one track but when I subscribe to several streams in a room and receive multiple tracks , it appears that the tracks are being disposed later on and can not be presented. In the web API there is a clone method to the track, is there any option to clone the track in the native API?

**Comment by okdevy** [comment]
Hello @cloudwebrtc. I ran into the same issue but I am trying have 3 transceivers at a time. With iOS it works great. But there is issue with android(Xiaomi). It seems that _initRemoteScreenShareRenderer is working but this one  _initRemoteRenderer shows this exception:

E/FlutterWebRTCPlugin( 7734): tryAddRendererToVideoTrack java.lang.IllegalStateException: MediaStreamTrack has been disposed.

```
 @override
  void onTrack(RTCTrackEvent event) {
    logger.info(
      'onTrack: ${event.track.kind}, id: ${event.track.id}, '
      ' mid: ${event.transceiver?.mid}, enabled: ${event.track.enabled}',
    );

    if (event.track.kind == 'video' && event.transceiver!.mid == '1') {
      unawaited(_initRemoteRenderer(event.track));
    }

    if (event.track.kind == 'video' && event.transceiver!.mid == '2') {
      unawaited(_initRemoteScreenShareRenderer(event.track));
    }

    event.track.onEnded = () async {
      logger.info('Remote track ended: ${event.track.id}');
      await _disposeRemoteRenderer();
      await _disposeRemoteScreenShareRenderer();
    };

    super.onTrack(event);
  } 

Future<void> _initRemoteRenderer(MediaStreamTrack track) async {
    remoteStream = await createLocalMediaStream(track.id!);

    await remoteStream!.addTrack(track);

    if (_remoteRenderer != null) {
      _remoteRenderer!.srcObject = remoteStream;

      _delegate.onRemoteVideoAvailable(_remoteRenderer!.info);

      return;
    }

    final remoteRenderer = RTCVideoRenderer();

    await remoteRenderer.initialize();
    remoteRenderer
      ..onFirstFrameRendered = () {
        logger.info('remoteRenderer.onFirstFrameRendered');
        _delegate.onRemoteVideoAvailable(remoteRenderer.info);
      }
      ..onResize = () {
        _delegate.onRemoteVideoAvailable(remoteRenderer.info);
        logger.info('remoteRenderer.onResize');
      }
      ..srcObject = remoteStream;

    _remoteRenderer = remoteRenderer;

    _delegate.onRemoteCameraControl(isEnabled: true);
  }



Future<void> _initRemoteScreenShareRenderer(MediaStreamTrack track) async {
    screenShareStream = await createLocalMediaStream(
      'screen-share',
    );
    await screenShareStream!.addTrack(track);

    if (_remoteScreenShareRenderer != null) {
      _remoteScreenShareRenderer!.srcObject = screenShareStream;

      _delegate.onRemoteScreenShareVideoAvailable(
        _remoteScreenShareRenderer!.info,
      );

      return;
    }

    final remoteScreenShareRenderer = RTCVideoRenderer();
    await remoteScreenShareRenderer.initialize();
    remoteScreenShareRenderer
      ..onFirstFrameRendered = () {
        logger.info('remoteScreenShareRenderer.onFirstFrameRendered');
        _delegate.onRemoteScreenShareVideoAvailable(
          remoteScreenShareRenderer.info,
        );
      }
      ..onResize = () {
        _delegate.onRemoteScreenShareVideoAvailable(
          remoteScreenShareRenderer.info,
        );
        logger.info('remoteScreenShareRenderer.onResize');
      }
      ..srcObject = screenShareStream;

    _remoteScreenShareRenderer = remoteScreenShareRenderer;
  }

```

ontrack - called 3 times and only the last one works. 

any thoughts? 

With iOS I can show two camera views local and remote and remote screen sharing. But with android it seems not working
