### ISSUE TITLE
setVolume not working on multiple peers

### ISSUE THREAD

**Issue by gibson-luo** [flutter-webrtc/flutter-webrtc#469]
**Describe the bug**
If I'm connecting 2 peers, I'm not able to mute/unmute the first remote audio track, but it's fine for second one.

**To Reproduce**
1. connect 2 peers A and B one by one
2. mute A 
`pcA.getRemoteStreams()[0].getAudioTracks()[0].setVolume(0);`
this is not working for A, but it mutes B

**Expected behavior**
should be able to mute/unmute the previous peers, not just the last one

**Platform information**
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-CA)
    • Flutter version 1.22.6 at /Users/lzrgibson/flutterWorkspace/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/lzrgibson/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Gibson’s Xs (mobile) • 00008020-000D2D1C2679002E • ios • iOS 14.4

**Plugin version**:
0.5.8

**Comment by GeorgeAmgad** [comment]
I encountered the same issue with remote streams after adding an additional peer, it turned out that the sdp of all the incomming offers contains the same `msid` and `mslabel` that translate to the stream-id and track-id of the remote `MediaStream` so whenever you apply an operation on remote streams or remote tracks, internally, all of them are mapped and considered the same, so the behavior gets confusing.

 I could dive deeper into the reason of this particular behavior, but this should be enough to point you to the main problem.
 
 hope it's not too late 😄
