### ISSUE TITLE
.getUserMedia crashing while Chrome is in debug mode

### ISSUE THREAD

**Issue by jaydanurwin** [flutter-webrtc/flutter-webrtc#486]
**Describe the bug**

Using `.getUserMedia` crashes Chrome while running in debug mode. However, if you build the app and deploy it to web hosting it works fine.

**To Reproduce**

You can even see this if you run the example's code on this repo. Chrome crashes running the app locally in debug mode.

If you switch this line from

``` 
var stream = await navigator.mediaDevices.getUserMedia(mediaConstraints);
```

to 

``` 
var stream = await navigator.mediaDevices.getDisplayMedia(mediaConstraints);
```

it will get the user's shared screen and works great.

**Expected behavior**

It should work in both debug or release mode. This is extremely frustrating because the only way I can manually test my code accessing the video camera is if I build the app for release.

**Platform information**

* **Flutter version**: `[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-US)
    • Flutter version 2.0.0 at /Users/jaydanurwin/...
    • Framework revision 60bd88df91 (25 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
`
* **Plugin version**: flutter_webrtc: ^0.5.8
* **Platform**: Web is the platform target
* **OS version**: macOS
* **OS version**: macOS 11.2.2

**Comment by cloudwebrtc** [comment]
Hey, @jaydanurwin，are there any chrome console logs available?

**Comment by jaydanurwin** [comment]
Since Flutter web runs Chrome in a separate instance in debug mode is there an easy way to gather those logs? For me, Chrome is completely crashing and quiting so there's no way to open the console in time.

**Comment by cloudwebrtc** [comment]
It is not common to cause chrome to completely crash and launch. The flutter-webrtc web implementation part simply encapsulates the webrtc js API. It should not cause the crash. It seems to be caused by the development environment of flutter. I have no idea about it :(

BTW, If you are launching a chrome or flutter macOS app from vscode or terminal use `flutter run -d chrome|macos`, you should check the system settings' security & privacy. Among them, vscode and terminal have camera/microphone permission enabled, if not set, it will cause flutter mac app to directly apply for camera permission Crashes, I don’t know if chrome has the same problem, but you can try it

**Comment by jaydanurwin** [comment]
That was it! It turns out it was VS Code not having/asking for access to the mic/camera. I ran `flutter run -d chrome` from iTerm instead of running it inside VS Code, it asked for permissions, I allowed them and it worked just fine. I'll +1 the linked VS Code issue. 👍🏼

**Comment by jaydanurwin** [comment]
For anyone else experiencing this issue please read comment above. If you run the app from VS Code and VS Code has not yet been given camera or microphone permissions it will crash Chrome. The solution is to either manually force VS Code to ask for permissions (in the issue linked above) or run your flutter app from another app instead of VS Code.
