### ISSUE TITLE
RTCDataChannel.send should return Future<bool>

### ISSUE THREAD

**Issue by rostopira** [flutter-webrtc/flutter-webrtc#78]
Pretty self-explanatory
Native DataChannel may not be connected yet to remote peer or just failed for some reason
I've checked, both native implementations return boolean

**Comment by wer-mathurin** [comment]
Hi @rostopira ,

The current implementation of Android, IOs and Mac return a success with a null value.  The requirement is that you would need react if it succeed or not?

@cloudwebrtc : Since returning null is not a good practice, maybe we can just change the native implementation to return a boolean instead of null.  I don't have experience with writing native ios and mac code , but seems simple as changing in Java the result.success(null) to result.success(true) and but my guess would be changing result(nil) => result(true) for the mac and iOs implementation.

**Comment by wer-mathurin** [comment]
@rostopira :  Still required?  And can you confirm you sees the same thing as me for the native implementation?  willing to do a PR to change the native code?
