### ISSUE TITLE
register call 

### ISSUE THREAD

**Issue by Jliberatomex** [flutter-webrtc/flutter-webrtc#971]
Hi i have a question 

is possible get register call?

**Comment by cloudwebrtc** [comment]
do you mean register VoIP call or something? flutter-webrtc is a package for webrtc native SDK, you can design your system in any way you like, for example, p2p call, sip/VoIP client. But the plugin itself does not provide any signaling and system functions.

**Comment by ycherniavskyi** [comment]
It seems that you have no whole picture about WebRTC (its goal and functionality), so I could recommend you to read through [WebRTC API](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API).

And answering your particular question - not, it is not possible to get the information regarding these video calls made. Because WebRTC is not about calls. It is about streams.
